### ISSUE TITLE
update to 3.7.9

### ISSUE THREAD

**Issue by innawe** [lolbackdoor/TheSnkrsBot#3]
Hello, this isnt a issue i want to Thanks You for the bot. 
How to update to the last version (3.7.9)? 
Thanks in advance
Have a nice day

**Comment by ShaneAbara** [comment]
need to update too :( 

SNKRS stuck on "Adding"

**Comment by lolbackdoor** [comment]
Updated.

**Comment by ShaneAbara** [comment]
Thank you! Is there a way to donate?
